
public enum Operations {
    EQ, NE, LT, LE, GT, GE, AND, OR, NOT, MATCH, NOTMATCH, DOLLAR,
    PREINC,POSTINC,PREDEC, POSTDEC,UNARYPOS, UNARYNEG, IN,
    EXPONENT, ADD, SUBTRACT,MULTIPLY, DIVIDE,MODULO, CONCATENATION

}
