
public enum TokenType {

    WORD, NUMBER, SEPARATOR, FOR, DO, WHILE, IF, BREAK, 
    CONTINUE, ELSE, RETURN, BEGIN, END, PRINT, PRINTF, 
    NEXT, IN, DELETE, GETLINE, EXIT, NEXTFILE, FUNCTION,
    STRINGLITERAL, EXPONENT, MATCH, APPEND, LEFTCURLYBRACKET, RIGHTCURLYBRACKET,LEFTBRACKET,RIGHTBRACKET
    , LEFTPARENTHESIS ,RIGHTPARENTHESIS, DOLLARSIGN, EQUAL, LESSTHAN, GREATERTHAN, 
    NOT, PLUS, MINUS, COLON, SEMICOLON, MULTIPLY, DIVIDE, MODULUS,
    OR, ESCAPE, TERNARYOPERATOR, GREATERTHANOREQUALTO, PLUSPLUS, MINUSMINUS,
    LESSTHANOREQUALTO, NOTEQUAL, EXPONENTEQUAL, 
    MODULUSEQUAL, MULTIPLYEQUAL, DIVIDEEQUAL, PLUSEQUAL, MINUSEQUAL,
    NOTMATCH, AND, EQUALEQUAL, REGULAREXPRESSION, COMMA, PATTERN
    
}
